import { Layout as SectionIcon, Columns3, Square, MoveVertical, Minus } from "lucide-react";
import type { BlockDefinition } from "@/lib/registry-types";
import {
  SectionBlock,
  ColumnsBlock,
  ColumnBlock,
  SpacerBlock,
  DividerBlock,
} from "./layout";

export const layoutBlocks: BlockDefinition[] = [
  {
    type: "section",
    label: "Section",
    icon: SectionIcon,
    category: "Layout",
    description: "Full-width band that holds other blocks",
    isContainer: true,
    emptyMinHeight: 80,
    defaultProps: {},
    defaultStyles: {
      desktop: {
        paddingTop: "64px",
        paddingBottom: "64px",
        paddingLeft: "24px",
        paddingRight: "24px",
        backgroundColor: "#ffffff",
      },
    },
    fields: [],
    styleGroups: ["background", "spacing", "border", "layout"],
    Render: SectionBlock,
  },
  {
    type: "columns",
    label: "Columns",
    icon: Columns3,
    category: "Layout",
    description: "A responsive row of columns",
    isContainer: true,
    defaultProps: { layout: "1-1" },
    defaultStyles: { desktop: {} },
    fields: [
      {
        key: "layout",
        label: "Layout",
        type: "select",
        options: [
          { label: "1 column", value: "1" },
          { label: "2 columns", value: "1-1" },
          { label: "3 columns", value: "1-1-1" },
          { label: "4 columns", value: "1-1-1-1" },
          { label: "Sidebar left (1:2)", value: "1-2" },
          { label: "Sidebar right (2:1)", value: "2-1" },
        ],
      },
    ],
    styleGroups: ["spacing", "layout"],
    Render: ColumnsBlock,
    containerStrategy: "fixed",
    defaultChildren: ["column", "column"],
  },
  {
    type: "column",
    label: "Column",
    icon: Square,
    category: "Layout",
    description: "A single column cell",
    isContainer: true,
    emptyMinHeight: 64,
    defaultProps: {},
    defaultStyles: { desktop: {} },
    fields: [],
    styleGroups: ["background", "spacing", "border", "layout"],
    Render: ColumnBlock,
  },
  {
    type: "spacer",
    label: "Spacer",
    icon: MoveVertical,
    category: "Layout",
    description: "Vertical empty space",
    defaultProps: { height: 48 },
    defaultStyles: { desktop: {} },
    fields: [{ key: "height", label: "Height (px)", type: "number" }],
    styleGroups: [],
    Render: SpacerBlock,
  },
  {
    type: "divider",
    label: "Divider",
    icon: Minus,
    category: "Layout",
    description: "A horizontal line",
    defaultProps: { color: "#e2e8f0", thickness: 1, width: "100%", lineStyle: "solid" },
    defaultStyles: { desktop: { paddingTop: "8px", paddingBottom: "8px" } },
    fields: [
      { key: "color", label: "Color", type: "color" },
      { key: "thickness", label: "Thickness (px)", type: "number" },
      { key: "width", label: "Width", type: "text", placeholder: "100% or 200px" },
      {
        key: "lineStyle",
        label: "Style",
        type: "select",
        options: [
          { label: "Solid", value: "solid" },
          { label: "Dashed", value: "dashed" },
          { label: "Dotted", value: "dotted" },
        ],
      },
    ],
    styleGroups: ["spacing"],
    Render: DividerBlock,
  },
];
